# Generated by Django 4.1.3 on 2022-11-03 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_dish'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='price',
            field=models.IntegerField(blank=True, default=0, verbose_name='Цена порции'),
        ),
        migrations.AddField(
            model_name='dish',
            name='wight',
            field=models.IntegerField(blank=True, default=0, verbose_name='Масса порции'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/dishes/', verbose_name='Изображение блюда'),
        ),
    ]
