# Generated by Django 4.1.3 on 2022-11-03 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_dish_price_dish_wight_alter_dish_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='category',
            field=models.ForeignKey(blank=True, default=2, on_delete=django.db.models.deletion.CASCADE, to='menu.category', verbose_name='Категория блюда'),
            preserve_default=False,
        ),
    ]
