# Generated by Django 4.1.3 on 2022-11-03 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_dish_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Отображение на сайте'),
        ),
    ]
