# Generated by Django 4.1.3 on 2022-11-05 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orders',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name': 'Статус заказа', 'verbose_name_plural': 'Статусы заказа'},
        ),
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.ForeignKey(default='Новый', on_delete=django.db.models.deletion.CASCADE, to='orders.status', verbose_name='Статус заказа'),
        ),
    ]
