# Generated by Django 4.1.3 on 2022-11-05 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_dish_is_published'),
        ('orders', '0003_alter_orders_status_dishesincart'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='dishes',
            field=models.ManyToManyField(to='orders.dishesincart', verbose_name='Блюда в заказе>'),
        ),
        migrations.AlterField(
            model_name='dishesincart',
            name='count',
            field=models.IntegerField(default=0, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='dishesincart',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.dish', verbose_name='Продукт'),
        ),
    ]
